---
name: Build / Swift

on:
  pull_request:
    paths:
      - apps/otel-swift/**
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift-version: ["5.10.1", "6.0", "6.1.0"]

    name: Swift ${{ matrix.swift-version }}

    steps:
      - name: ğŸšš Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: ğŸ‰ Setup Swift
        uses: swift-actions/setup-swift@682457186b71c25a884c45c06f859febbe259240 # v2.3.0
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: âœ… Build application
        run: swift build

      # - name: âœ… Run tests
      #   run: swift test

      - name: âœ… Run SwiftLint
        uses: norio-nomura/action-swiftlint@9f4dcd7fd46b4e75d7935cf2f4df406d5cae3684 # v3.2.1
        with:
          args: --strict

  docker:
    runs-on: ubuntu-latest
    needs: build
    name: Docker packaging
    steps:
      - name: ğŸšš Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: ğŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: ğŸ³ Log in to Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ³ Extract metadata
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: ğŸ³ Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ./apps/otel-swift
          file: ./apps/otel-swift/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          # provenance: mode=max
          # sbom: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
